name: our-life-after-corona

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: true
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      IMAGE_TAG: eljenso/our-life-after-corona:$GITHUB_SHA
    steps:
    - uses: actions/checkout@v2

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: eljenso/our-life-after-corona
        username: ${{ secrets.DOCKER_HUB_LOGIN_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_LOGIN_PASSWORD }}
